### ISSUE TITLE
右侧目录fix失效

### ISSUE THREAD

**Issue by niceRAM** [niceRAM/nicesima#3]

**Comment by niceRAM** [comment]
未导入```jQuery```库，通过修改以下博客配置追加自定义 js 即可修复

```toml
# config.toml

[params]
  [params.custom]
  js = ["https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"]

```
